typography_spectrum: 0.030145953875035048
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4034557205159217
  lightness: 0.07446223357692361
  saturation: 0.401803539134562
  rhythmicContrast: 0.3741218198556453
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1795874407980591
analytics:
  google: null
  facebook: null
  twitter: null
name: CUTHRU
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ' made. Well and with care.'
description: Made. Well and with care.  Solutions for creative problems.
purpose: []
